import {Form, Button, message, Upload, Col, Tooltip, Row} from "antd";
import {QuestionCircleOutlined, UploadOutlined} from "@ant-design/icons";
import Link from "next/link";
import Image from "next/image";

export default function LabelsFileUpload(props){

    const settingLabels = {
        name: 'labelsFile',
        required: true,
        beforeUpload: (file) => {
            let filenameArr = file.name.split('.');
            props.setFileList([file]);
            let limitM = 5; //MB
            let isLabels = filenameArr[filenameArr.length - 2] === 'txt' ||
                filenameArr[filenameArr.length - 2] === 'csv' ||
                filenameArr[filenameArr.length - 2] === 'tsv';
            let isGzip = file.type === 'application/x-gzip' || file.type === 'application/gzip';
            let isZip = file.type === 'application/zip' || file.type === 'application/x-zip' ||
                file.type === 'application/x-zip-compressed'
            let isCompressed = isGzip||isZip
            let isLimit = file.size / 1024 / 1024 <= limitM;
            if (!isLabels || !isCompressed) {
                props.setFileList([])
                message.error({
                    content:`File: ${file.name} is not a compressed csv/tsv/txt format label file`,
                    style:{
                        marginTop: '12vh',
                    },
                    duration:3,
                });
            }
            if (!isLimit) {
                props.setFileList([])
                message.error({
                    content:`File: ${file.name} exceeds the limit: 5 MB`,
                    style:{
                        marginTop: '12vh',
                    },
                    duration:3,
                });
            }
            return false
        },
        onRemove: (file) => {
            if(props.uploading === false){
                const index = props.fileList.indexOf(file);
                const newFileList = props.fileList.slice();
                newFileList.splice(index, 1);
                props.setFileList(newFileList);
            }
        },
        fileList:props.fileList.slice(-1),//保留最后一个文件
        progress: {
            strokeColor: {
                '0%': '#3f10e9',
                '100%': '#2e0f8c',
            },
            strokeWidth: 3,
        }
    };

    const  toolTipText = <>
        <span>&gt; File Context:</span><br/>
        <span>
            This file is generated by users after assigning cell type identity to clusters in scRNA-seq analysis.
            The file must contain <b>two necessary columns</b>: 1) the first column must be the unique
            <b style={{color:"#a680ff"}}> &quot;cell_id&quot; </b>in line with count matrix file;
            2) the column indicating cell type identity must be titled with <b style={{color:"#a680ff"}}>&quot;cell_type&quot;</b>.
            Formats accepted are .csv, .tsv and .txt in .gz/zip compression. Click on &quot;?&quot; to learn more.
        </span><br/>
        <span>&gt; Example:</span><br/>
        <Image src={`/images/labels_example.png`} alt="..." width={400} height={130}/>
    </>

    return(
        <Row justify={"start"}>
            <Col span={16}>
                <Form.Item name="labelsFile" label="Label File"
                           rules={[
                               {
                                   required: true,
                               },
                           ]}
                >
                    <Upload {...settingLabels} maxCount={1}>
                        <Button type={"primary"} icon={<UploadOutlined />} ghost>Select a label file</Button>
                    </Upload>
                </Form.Item>
            </Col>
            <Col span={7}>
                <small style={{color:"gray"}}> (only a .gz/zip format file) </small>
                <Link href={'/tutorial/mapping/getStarted/#data_preparation'} target={"_blank"}>
                    <a target={'_blank'} rel={"noreferrer"}>
                        <Tooltip placement="topLeft"
                                 title={toolTipText}
                                 overlayInnerStyle={{width:400}}
                        >
                            <QuestionCircleOutlined />
                        </Tooltip>
                    </a>
                </Link>
            </Col>
        </Row>
    )
}