import {Form, Button, message, Upload, Col, Tooltip, Row} from "antd";
import {QuestionCircleOutlined, UploadOutlined} from "@ant-design/icons";
import Link from "next/link";
import Image from "next/image";

export default function LabelsFileUpload(props){

    const settingLabels = {
        name: 'labelsFile',
        required: true,
        beforeUpload: (file) => {
            let filenameArr = file.name.split('.');
            props.setFileList([file]);
            let limitM = 5; //MB
            let isLabels = filenameArr[filenameArr.length - 2] === 'txt' ||
                filenameArr[filenameArr.length - 2] === 'csv' ||
                filenameArr[filenameArr.length - 2] === 'tsv';
            let isGzip = file.type === 'application/x-gzip';
            let isZip = file.type === 'application/zip'
            let isLimit = file.size / 1024 / 1024 <= limitM;
            if (!isLabels || !(isGzip||isZip)) {
                props.setFileList([])
                message.error({
                    content:`File: ${file.name} is not a compressed csv/tsv/txt format label file`,
                    style:{
                        marginTop: '12vh',
                    },
                    duration:3,
                });
            }
            if (!isLimit) {
                props.setFileList([])
                message.error({
                    content:`File: ${file.name} exceeds the limit: 5 MB`,
                    style:{
                        marginTop: '12vh',
                    },
                    duration:3,
                });
            }
            return false
        },
        onRemove: (file) => {
            const index = props.fileList.indexOf(file);
            const newFileList = props.fileList.slice();
            newFileList.splice(index, 1);
            props.setFileList(newFileList);
        },
        fileList:props.fileList.slice(-1),//保留最后一个文件
    };

    const  toolTipText = <>
        <span>&gt; File Context:</span><br/>
        <span>
            This file is generated by users after you have annotated each cluster identified in scRNA-seq.
            The file contains <b>two columns</b>: unique<b style={{color:"#a680ff"}}> "cell_id" </b>
            must in first column, indicating the name of the cell; and <b style={{color:"#a680ff"}}>"cell_type"</b>,
            indicating the name of the cluster considered. Formats accepted are .csv .tsv and .txt in .gz/zip compression.
            Click on 'Question' to see more.
        </span><br/>
        <span>&gt; Example:</span><br/>
        <Image src={`/images/labels_example.png`} alt="..." width={400} height={130}/>

    </>

    return(
        <Row justify={"start"}>
            <Col span={16}>
                <Form.Item name="labelsFile" label="Label File"
                           rules={[
                               {
                                   required: true,
                               },
                           ]}
                >
                    <Upload {...settingLabels} maxCount={1}>
                        <Button type={"primary"} icon={<UploadOutlined />} ghost>Select a label file</Button>
                    </Upload>
                </Form.Item>
            </Col>
            <Col span={7}>
                <small style={{color:"gray"}}> (only a .gz/zip format file) </small>
                <Link href={'help/manual/annotation#format_uploaded_files'} target={"_blank"}>
                    <a target={'_blank'} rel={"noreferrer"}>
                        <Tooltip placement="topLeft"
                                 title={toolTipText}
                                 overlayInnerStyle={{width:400}}
                        >
                            <QuestionCircleOutlined />
                        </Tooltip>
                    </a>
                </Link>
            </Col>
        </Row>
    )
}